version: "3.6"
services:
  agathadb:
    image: postgres:11-alpine
    restart: always
    container_name: agathadb
    environment:
      POSTGRES_PASSWORD: gestaoriscos
      POSTGRES_USER: gestaoriscos
      POSTGRES_DB: agatha
  agatha:
    image: lucasdiedrich/agatha
    restart: always
    container_name: agatha
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   CASO FOR UTILIZAR VARIAVEIS DE AMBIENTE NÃO DESCOMENTAR A LINHA ABAIXO
    #   - "/volumes/agatha/config:/config"
    #   - "/etc/localtime:/etc/localtime"
    environment:
      # DB_HOST: agathadb
      # DB_PASSWORD: gestaoriscos
      # DB_USER: gestaoriscos
      # DB_NAME: agatha
      # DB_CHECK: 0
      # CONF_CHECK: 0
      # ECIDADAO_ENV: PROD | TESTE
      # ECIDADAO_SERVER: MINHAINSTITUICAO.EDU.BR
      # ECIDADAO_ID: MINHAID
      # ECIDADAO_SECRET: mINHAKEY
      # SIORG: CODIGO SIORG DA MINHA INSTITUIÇÃO
      # EMAIL_SERVIDOR: ENDEREÇO DO SERVIDOR DE E-MAIL DA INSTITUIÇÃO
      # EMAIL_USUARIO: USUÁRIO DE ACESSO AO SERVIDOR DE E_MAIL
      # EMAIL_SENHA: SENHA DE ACESSO AO SERVIDOR DE EMAIL
      # EMAIL_AUTENTICACAO: true | false #DEFINE SE O SERVIDOR DE EMAIL IRA NECESSITAR DE AUTENTICAÇÃO DE USUÁRIO
      # EMAIL_PORTA: PORTA PARA ACESSO AO SERVIDOR DE E-MAIL
      # EMAIL_REMETENTE: COLOCAR E-MAIL REMETENTE INSTITUCIONAL
      # EMAIL_DESTINATARIO: COLOCAR E-MAIL REMETENTE INSTITUCIONAL
      # EMAIL_FALECONOSCO: COLOCAR E-MAIL PARA CONTATO
    depends_on:
     - agathadb
